'use client';

import React from 'react';
// Devicons - Programming languages and tech logos
import {
  ReactOriginal,
  NextjsOriginal,
  TypescriptOriginal,
  JavascriptOriginal,
  Html5Original,
  Css3Original,
  TailwindcssOriginal,
  VuejsOriginal,
  AngularOriginal,
  SvelteOriginal,
  NodejsOriginal,
  ExpressOriginal,
  NestjsOriginal,
  DotnetcoreOriginal,
  PythonOriginal,
  FastapiOriginal,
  DjangoPlain,
  FlaskOriginal,
  JavaOriginal,
  SpringOriginal,
  GoOriginal,
  RustOriginal,
  CplusplusOriginal,
  CsharpOriginal,
  PhpOriginal,
  LaravelOriginal,
  RubyOriginal,
  RailsPlain,
  PostgresqlOriginal,
  MysqlOriginal,
  MongodbOriginal,
  RedisOriginal,
  FirebaseOriginal,
  SupabaseOriginal,
  GraphqlPlain,
  DockerOriginal,
  KubernetesOriginal,
  AmazonwebservicesOriginalWordmark,
  AzureOriginal,
  GooglecloudOriginal,
  VercelOriginal,
  NetlifyOriginal,
  DigitaloceanOriginal,
  LinuxOriginal,
  UbuntuOriginal,
  NginxOriginal,
  ApacheOriginal,
  GitOriginal,
  GithubOriginal,
  GitlabOriginal,
  BitbucketOriginal,
  VscodeOriginal,
  JetbrainsOriginal,
  FigmaOriginal,
  JestPlain,
  VitejsOriginal,
  WebpackOriginal,
  BabelOriginal,
  NpmOriginalWordmark,
  YarnOriginal,
  PnpmOriginal,
  ElectronOriginal,
  ReactnativeOriginal,
  FlutterOriginal,
  SwiftOriginal,
  KotlinOriginal,
  AndroidOriginal,
  AppleOriginal,
  SassOriginal,
  LessPlainWordmark,
  BootstrapOriginal,
  MaterialuiOriginal,
  ThreejsOriginal,
  D3jsOriginal,
  ReduxOriginal,
  MobxOriginal,
  SocketioOriginal,
  JqueryOriginal,
  GulpPlain,
  GruntOriginal,
  AnsibleOriginal,
  TerraformOriginal,
  JenkinsOriginal,
  CircleciPlain,
  TravisPlain,
  SentryOriginal,
  GrafanaOriginal,
  PrometheusOriginal,
  ElasticsearchOriginal,
  RabbitmqOriginal,
  ApachekafkaOriginal,
  SqliteOriginal,
  OracleOriginal,
  MicrosoftsqlserverOriginal,
  MarkdownOriginal,
  LatexOriginal,
  BlenderOriginal,
  UnityOriginal,
  UnrealengineOriginal,
  PrismaOriginal,
  SequelizeOriginal,
  AdonisjsOriginal,
  SolidjsOriginal,
  QwikOriginal,
  AstroOriginal,
  RemixOriginal,
  GatsbyOriginal,
  StorybookOriginal,
  CypressioOriginal,
  PlaywrightOriginal,
  VitestOriginal,
  PostmanOriginal,
  InsomniaOriginal,
  SwaggerOriginal,
  OpenapiOriginal,
  OktaOriginal,
  SlackOriginal,
  NotionOriginal,
  JiraOriginal,
  ConfluenceOriginal,
  TrelloOriginal,
  FigmaOriginal as FigmaIcon,
  CanvaOriginal,
  PhotoshopOriginal,
  IllustratorOriginal,
  XdOriginal,
  SketchOriginal,
  FramermotionOriginal,
  WordpressOriginal,
  WoocommerceOriginal,
  MagentoOriginal,
  BunOriginal,
  DenojsOriginal,
  EslintOriginal,
  SonarqubeOriginal,
  DatadogOriginal,
  NewrelicOriginal,
  CloudflareOriginal,
  DynamodbOriginal,
} from 'devicons-react';

// Simple Icons from react-icons for additional brands (only the ones used in techIcons)
import {
  SiOpenai,
  SiAnthropic,
  SiHuggingface,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiJupyter,
  SiLangchain,
  SiRailway,
  SiRender,
  SiFlydotio,
  SiPlanetscale,
  SiUpstash,
  SiTurso,
  SiElixir,
  SiDrizzle,
  SiPrettier,
  SiDiscord,
  SiContentful,
  SiStrapi,
  SiShopify,
  SiStripe,
  SiSanity,
  SiGhost,
  SiWebflow,
  SiFramer,
} from 'react-icons/si';

// Lucide icons for general purpose
import {
  Code2,
  Database,
  Cloud,
  Server,
  Globe,
  Terminal,
  Cpu,
  Smartphone,
  Monitor,
  Palette,
  Wrench,
  Settings,
  Lock,
  Zap,
  BarChart3,
  MessageSquare,
  Mail,
  Video,
  Music,
  Image,
  FileText,
  Folder,
  Search,
  Shield,
  Bug,
  TestTube,
  Rocket,
  Package,
  Layers,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Container,
  Network,
  Wifi,
  HardDrive,
  MemoryStick,
  Binary,
  Braces,
  Hash,
  AtSign,
  Link,
  ExternalLink,
  Download,
  Upload,
  RefreshCw,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  EyeOff,
  Bell,
  BellOff,
  Calendar,
  Clock,
  Timer,
  Hourglass,
  Activity,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  AreaChart,
} from 'lucide-react';

// Tech icon configuration with categories
export interface TechIcon {
  id: string;
  name: string;
  icon: React.ComponentType<{ size?: number; className?: string }>;
  category: 'frontend' | 'backend' | 'database' | 'devops' | 'tools' | 'mobile' | 'ai' | 'cloud' | 'other';
  color?: string;
}

export const techIcons: TechIcon[] = [
  // Frontend
  { id: 'react', name: 'React', icon: ReactOriginal, category: 'frontend', color: '#61DAFB' },
  { id: 'nextjs', name: 'Next.js', icon: NextjsOriginal, category: 'frontend', color: '#000000' },
  { id: 'typescript', name: 'TypeScript', icon: TypescriptOriginal, category: 'frontend', color: '#3178C6' },
  { id: 'javascript', name: 'JavaScript', icon: JavascriptOriginal, category: 'frontend', color: '#F7DF1E' },
  { id: 'html5', name: 'HTML5', icon: Html5Original, category: 'frontend', color: '#E34F26' },
  { id: 'css3', name: 'CSS3', icon: Css3Original, category: 'frontend', color: '#1572B6' },
  { id: 'tailwindcss', name: 'Tailwind CSS', icon: TailwindcssOriginal, category: 'frontend', color: '#06B6D4' },
  { id: 'vuejs', name: 'Vue.js', icon: VuejsOriginal, category: 'frontend', color: '#4FC08D' },
  { id: 'angular', name: 'Angular', icon: AngularOriginal, category: 'frontend', color: '#DD0031' },
  { id: 'svelte', name: 'Svelte', icon: SvelteOriginal, category: 'frontend', color: '#FF3E00' },
  { id: 'solidjs', name: 'SolidJS', icon: SolidjsOriginal, category: 'frontend', color: '#2C4F7C' },
  { id: 'qwik', name: 'Qwik', icon: QwikOriginal, category: 'frontend', color: '#AC7EF4' },
  { id: 'astro', name: 'Astro', icon: AstroOriginal, category: 'frontend', color: '#FF5D01' },
  { id: 'remix', name: 'Remix', icon: RemixOriginal, category: 'frontend', color: '#000000' },
  { id: 'gatsby', name: 'Gatsby', icon: GatsbyOriginal, category: 'frontend', color: '#663399' },
  { id: 'sass', name: 'Sass', icon: SassOriginal, category: 'frontend', color: '#CC6699' },
  { id: 'bootstrap', name: 'Bootstrap', icon: BootstrapOriginal, category: 'frontend', color: '#7952B3' },
  { id: 'materialui', name: 'Material UI', icon: MaterialuiOriginal, category: 'frontend', color: '#007FFF' },
  { id: 'threejs', name: 'Three.js', icon: ThreejsOriginal, category: 'frontend', color: '#000000' },
  { id: 'd3js', name: 'D3.js', icon: D3jsOriginal, category: 'frontend', color: '#F9A03C' },
  { id: 'redux', name: 'Redux', icon: ReduxOriginal, category: 'frontend', color: '#764ABC' },
  { id: 'framermotion', name: 'Framer Motion', icon: FramermotionOriginal, category: 'frontend', color: '#0055FF' },
  { id: 'storybook', name: 'Storybook', icon: StorybookOriginal, category: 'frontend', color: '#FF4785' },

  // Backend
  { id: 'nodejs', name: 'Node.js', icon: NodejsOriginal, category: 'backend', color: '#339933' },
  { id: 'express', name: 'Express.js', icon: ExpressOriginal, category: 'backend', color: '#000000' },
  { id: 'nestjs', name: 'NestJS', icon: NestjsOriginal, category: 'backend', color: '#E0234E' },
  { id: 'dotnetcore', name: '.NET Core', icon: DotnetcoreOriginal, category: 'backend', color: '#512BD4' },
  { id: 'python', name: 'Python', icon: PythonOriginal, category: 'backend', color: '#3776AB' },
  { id: 'fastapi', name: 'FastAPI', icon: FastapiOriginal, category: 'backend', color: '#009688' },
  { id: 'django', name: 'Django', icon: DjangoPlain, category: 'backend', color: '#092E20' },
  { id: 'flask', name: 'Flask', icon: FlaskOriginal, category: 'backend', color: '#000000' },
  { id: 'java', name: 'Java', icon: JavaOriginal, category: 'backend', color: '#007396' },
  { id: 'spring', name: 'Spring', icon: SpringOriginal, category: 'backend', color: '#6DB33F' },
  { id: 'go', name: 'Go', icon: GoOriginal, category: 'backend', color: '#00ADD8' },
  { id: 'rust', name: 'Rust', icon: RustOriginal, category: 'backend', color: '#000000' },
  { id: 'cplusplus', name: 'C++', icon: CplusplusOriginal, category: 'backend', color: '#00599C' },
  { id: 'csharp', name: 'C#', icon: CsharpOriginal, category: 'backend', color: '#239120' },
  { id: 'php', name: 'PHP', icon: PhpOriginal, category: 'backend', color: '#777BB4' },
  { id: 'laravel', name: 'Laravel', icon: LaravelOriginal, category: 'backend', color: '#FF2D20' },
  { id: 'ruby', name: 'Ruby', icon: RubyOriginal, category: 'backend', color: '#CC342D' },
  { id: 'rails', name: 'Rails', icon: RailsPlain, category: 'backend', color: '#CC0000' },
  { id: 'graphql', name: 'GraphQL', icon: GraphqlPlain, category: 'backend', color: '#E10098' },
  { id: 'adonis', name: 'AdonisJS', icon: AdonisjsOriginal, category: 'backend', color: '#5A45FF' },
  { id: 'bun', name: 'Bun', icon: BunOriginal, category: 'backend', color: '#FBF0DF' },
  { id: 'deno', name: 'Deno', icon: DenojsOriginal, category: 'backend', color: '#000000' },
  { id: 'elixir', name: 'Elixir', icon: SiElixir, category: 'backend', color: '#4B275F' },

  // Database
  { id: 'postgresql', name: 'PostgreSQL', icon: PostgresqlOriginal, category: 'database', color: '#4169E1' },
  { id: 'mysql', name: 'MySQL', icon: MysqlOriginal, category: 'database', color: '#4479A1' },
  { id: 'mongodb', name: 'MongoDB', icon: MongodbOriginal, category: 'database', color: '#47A248' },
  { id: 'redis', name: 'Redis', icon: RedisOriginal, category: 'database', color: '#DC382D' },
  { id: 'firebase', name: 'Firebase', icon: FirebaseOriginal, category: 'database', color: '#FFCA28' },
  { id: 'supabase', name: 'Supabase', icon: SupabaseOriginal, category: 'database', color: '#3ECF8E' },
  { id: 'prisma', name: 'Prisma', icon: PrismaOriginal, category: 'database', color: '#2D3748' },
  { id: 'drizzle', name: 'Drizzle', icon: SiDrizzle, category: 'database', color: '#C5F74F' },
  { id: 'sqlite', name: 'SQLite', icon: SqliteOriginal, category: 'database', color: '#003B57' },
  { id: 'oracle', name: 'Oracle', icon: OracleOriginal, category: 'database', color: '#F80000' },
  { id: 'sqlserver', name: 'SQL Server', icon: MicrosoftsqlserverOriginal, category: 'database', color: '#CC2927' },
  { id: 'elasticsearch', name: 'Elasticsearch', icon: ElasticsearchOriginal, category: 'database', color: '#005571' },
  { id: 'dynamodb', name: 'DynamoDB', icon: DynamodbOriginal, category: 'database', color: '#4053D6' },
  { id: 'planetscale', name: 'PlanetScale', icon: SiPlanetscale, category: 'database', color: '#000000' },
  { id: 'upstash', name: 'Upstash', icon: SiUpstash, category: 'database', color: '#00E9A3' },
  { id: 'turso', name: 'Turso', icon: SiTurso, category: 'database', color: '#4FF8D2' },

  // DevOps & Cloud
  { id: 'docker', name: 'Docker', icon: DockerOriginal, category: 'devops', color: '#2496ED' },
  { id: 'kubernetes', name: 'Kubernetes', icon: KubernetesOriginal, category: 'devops', color: '#326CE5' },
  { id: 'aws', name: 'AWS', icon: AmazonwebservicesOriginalWordmark, category: 'cloud', color: '#FF9900' },
  { id: 'azure', name: 'Azure', icon: AzureOriginal, category: 'cloud', color: '#0078D4' },
  { id: 'googlecloud', name: 'Google Cloud', icon: GooglecloudOriginal, category: 'cloud', color: '#4285F4' },
  { id: 'vercel', name: 'Vercel', icon: VercelOriginal, category: 'cloud', color: '#000000' },
  { id: 'netlify', name: 'Netlify', icon: NetlifyOriginal, category: 'cloud', color: '#00C7B7' },
  { id: 'digitalocean', name: 'DigitalOcean', icon: DigitaloceanOriginal, category: 'cloud', color: '#0080FF' },
  { id: 'cloudflare', name: 'Cloudflare', icon: CloudflareOriginal, category: 'cloud', color: '#F38020' },
  { id: 'railway', name: 'Railway', icon: SiRailway, category: 'cloud', color: '#0B0D0E' },
  { id: 'render', name: 'Render', icon: SiRender, category: 'cloud', color: '#46E3B7' },
  { id: 'fly', name: 'Fly.io', icon: SiFlydotio, category: 'cloud', color: '#7B3BE2' },
  { id: 'linux', name: 'Linux', icon: LinuxOriginal, category: 'devops', color: '#FCC624' },
  { id: 'ubuntu', name: 'Ubuntu', icon: UbuntuOriginal, category: 'devops', color: '#E95420' },
  { id: 'nginx', name: 'Nginx', icon: NginxOriginal, category: 'devops', color: '#009639' },
  { id: 'apache', name: 'Apache', icon: ApacheOriginal, category: 'devops', color: '#D22128' },
  { id: 'terraform', name: 'Terraform', icon: TerraformOriginal, category: 'devops', color: '#7B42BC' },
  { id: 'ansible', name: 'Ansible', icon: AnsibleOriginal, category: 'devops', color: '#EE0000' },
  { id: 'jenkins', name: 'Jenkins', icon: JenkinsOriginal, category: 'devops', color: '#D24939' },
  { id: 'githubactions', name: 'GitHub Actions', icon: GithubOriginal, category: 'devops', color: '#2088FF' },
  { id: 'circleci', name: 'CircleCI', icon: CircleciPlain, category: 'devops', color: '#343434' },
  { id: 'grafana', name: 'Grafana', icon: GrafanaOriginal, category: 'devops', color: '#F46800' },
  { id: 'prometheus', name: 'Prometheus', icon: PrometheusOriginal, category: 'devops', color: '#E6522C' },

  // Tools
  { id: 'git', name: 'Git', icon: GitOriginal, category: 'tools', color: '#F05032' },
  { id: 'github', name: 'GitHub', icon: GithubOriginal, category: 'tools', color: '#181717' },
  { id: 'gitlab', name: 'GitLab', icon: GitlabOriginal, category: 'tools', color: '#FC6D26' },
  { id: 'bitbucket', name: 'Bitbucket', icon: BitbucketOriginal, category: 'tools', color: '#0052CC' },
  { id: 'vscode', name: 'VS Code', icon: VscodeOriginal, category: 'tools', color: '#007ACC' },
  { id: 'jetbrains', name: 'JetBrains', icon: JetbrainsOriginal, category: 'tools', color: '#000000' },
  { id: 'figma', name: 'Figma', icon: FigmaOriginal, category: 'tools', color: '#F24E1E' },
  { id: 'postman', name: 'Postman', icon: PostmanOriginal, category: 'tools', color: '#FF6C37' },
  { id: 'insomnia', name: 'Insomnia', icon: InsomniaOriginal, category: 'tools', color: '#4000BF' },
  { id: 'jest', name: 'Jest', icon: JestPlain, category: 'tools', color: '#C21325' },
  { id: 'vitest', name: 'Vitest', icon: VitestOriginal, category: 'tools', color: '#6E9F18' },
  { id: 'cypress', name: 'Cypress', icon: CypressioOriginal, category: 'tools', color: '#17202C' },
  { id: 'playwright', name: 'Playwright', icon: PlaywrightOriginal, category: 'tools', color: '#2EAD33' },
  { id: 'vite', name: 'Vite', icon: VitejsOriginal, category: 'tools', color: '#646CFF' },
  { id: 'webpack', name: 'Webpack', icon: WebpackOriginal, category: 'tools', color: '#8DD6F9' },
  { id: 'babel', name: 'Babel', icon: BabelOriginal, category: 'tools', color: '#F9DC3E' },
  { id: 'npm', name: 'npm', icon: NpmOriginalWordmark, category: 'tools', color: '#CB3837' },
  { id: 'yarn', name: 'Yarn', icon: YarnOriginal, category: 'tools', color: '#2C8EBB' },
  { id: 'pnpm', name: 'pnpm', icon: PnpmOriginal, category: 'tools', color: '#F69220' },
  { id: 'eslint', name: 'ESLint', icon: EslintOriginal, category: 'tools', color: '#4B32C3' },
  { id: 'prettier', name: 'Prettier', icon: SiPrettier, category: 'tools', color: '#F7B93E' },
  { id: 'swagger', name: 'Swagger', icon: SwaggerOriginal, category: 'tools', color: '#85EA2D' },
  { id: 'sentry', name: 'Sentry', icon: SentryOriginal, category: 'tools', color: '#362D59' },
  { id: 'notion', name: 'Notion', icon: NotionOriginal, category: 'tools', color: '#000000' },
  { id: 'jira', name: 'Jira', icon: JiraOriginal, category: 'tools', color: '#0052CC' },
  { id: 'slack', name: 'Slack', icon: SlackOriginal, category: 'tools', color: '#4A154B' },
  { id: 'discord', name: 'Discord', icon: SiDiscord, category: 'tools', color: '#5865F2' },

  // Mobile
  { id: 'reactnative', name: 'React Native', icon: ReactnativeOriginal, category: 'mobile', color: '#61DAFB' },
  { id: 'flutter', name: 'Flutter', icon: FlutterOriginal, category: 'mobile', color: '#02569B' },
  { id: 'swift', name: 'Swift', icon: SwiftOriginal, category: 'mobile', color: '#F05138' },
  { id: 'kotlin', name: 'Kotlin', icon: KotlinOriginal, category: 'mobile', color: '#7F52FF' },
  { id: 'android', name: 'Android', icon: AndroidOriginal, category: 'mobile', color: '#3DDC84' },
  { id: 'apple', name: 'Apple', icon: AppleOriginal, category: 'mobile', color: '#000000' },
  { id: 'electron', name: 'Electron', icon: ElectronOriginal, category: 'mobile', color: '#47848F' },

  // AI/ML
  { id: 'openai', name: 'OpenAI', icon: SiOpenai, category: 'ai', color: '#412991' },
  { id: 'anthropic', name: 'Anthropic', icon: SiAnthropic, category: 'ai', color: '#191919' },
  { id: 'huggingface', name: 'Hugging Face', icon: SiHuggingface, category: 'ai', color: '#FFD21E' },
  { id: 'tensorflow', name: 'TensorFlow', icon: SiTensorflow, category: 'ai', color: '#FF6F00' },
  { id: 'pytorch', name: 'PyTorch', icon: SiPytorch, category: 'ai', color: '#EE4C2C' },
  { id: 'langchain', name: 'LangChain', icon: SiLangchain, category: 'ai', color: '#1C3C3C' },
  { id: 'jupyter', name: 'Jupyter', icon: SiJupyter, category: 'ai', color: '#F37626' },
  { id: 'pandas', name: 'Pandas', icon: SiPandas, category: 'ai', color: '#150458' },
  { id: 'numpy', name: 'NumPy', icon: SiNumpy, category: 'ai', color: '#013243' },
  { id: 'scikitlearn', name: 'Scikit-learn', icon: SiScikitlearn, category: 'ai', color: '#F7931E' },

  // CMS & Content
  { id: 'wordpress', name: 'WordPress', icon: WordpressOriginal, category: 'other', color: '#21759B' },
  { id: 'sanity', name: 'Sanity', icon: SiSanity, category: 'other', color: '#F03E2F' },
  { id: 'contentful', name: 'Contentful', icon: SiContentful, category: 'other', color: '#2478CC' },
  { id: 'strapi', name: 'Strapi', icon: SiStrapi, category: 'other', color: '#4945FF' },
  { id: 'ghost', name: 'Ghost', icon: SiGhost, category: 'other', color: '#15171A' },
  { id: 'webflow', name: 'Webflow', icon: SiWebflow, category: 'other', color: '#4353FF' },
  { id: 'framer', name: 'Framer', icon: SiFramer, category: 'other', color: '#0055FF' },
  { id: 'shopify', name: 'Shopify', icon: SiShopify, category: 'other', color: '#7AB55C' },
  { id: 'stripe', name: 'Stripe', icon: SiStripe, category: 'other', color: '#008CDD' },
];

// Group icons by category
export const iconsByCategory = techIcons.reduce((acc, icon) => {
  if (!acc[icon.category]) {
    acc[icon.category] = [];
  }
  acc[icon.category].push(icon);
  return acc;
}, {} as Record<string, TechIcon[]>);

// Category labels
export const categoryLabels: Record<string, string> = {
  frontend: 'Frontend',
  backend: 'Backend',
  database: 'Database',
  devops: 'DevOps',
  cloud: 'Cloud',
  tools: 'Tools',
  mobile: 'Mobile',
  ai: 'AI / ML',
  other: 'Other',
};

// Get icon by ID
export function getIconById(id: string): TechIcon | undefined {
  return techIcons.find((icon) => icon.id === id);
}

// Icon component that renders based on ID
export function TechIcon({
  iconId,
  size = 24,
  className = '',
}: {
  iconId: string;
  size?: number;
  className?: string;
}) {
  const techIcon = getIconById(iconId);

  if (!techIcon) {
    return (
      <div
        className={`flex items-center justify-center rounded bg-zinc-800 ${className}`}
        style={{ width: size, height: size }}
      >
        <span className="text-xs font-bold text-zinc-500">?</span>
      </div>
    );
  }

  const IconComponent = techIcon.icon;
  return <IconComponent size={size} className={className} />;
}
